config/routes.rb
Wisdm::Application.routes.draw do

  resources :catalogs

  root to: "home#index"

  devise_for :users,
             :controllers  => {
               :registrations => 'my_devise/registrations',
               :sessions      => 'my_devise/sessions',
               :passwords     => 'my_devise/passwords',
               :unlocks       => 'my_devise/unlocks',
               :confirmations => 'my_devise/confirmations'
             }
  
  resources :users do
    collection do
      get :index
    end
    member do
      get :show, :following, :followers, :my_articles, :account
    end
    resources :friend_lists, only: [:create, :destroy]
  end

  resources :articles do

    post :add_property
    post :update_alternatives_order
    get  :show_participants
    post :like
    
    resources :alternatives do
      collection do
        get  :search
        post :search
        post :add
      end
    end

    resources :criteria, only: [:index, :create, :new]

    resources :watch_lists, only: [:create, :destroy]
    resources :participations do
      collection do
        get  :invite
        post :send_invitation
        get  :new_request
        post :send_request
        get  :assign_weights
        post :update_weights
      end
      member do
        post :approve
        post :confirm
      end
    end

    resources :comments, only: [:edit, :create, :update, :destroy]
  end

  resources :criteria do
    get :tree
    post :move
    get :aggregate_detail
    get :aggregate_summary

    resources :comparisons do
      collection do
        post :compare
        get :smart
        get :pairwise
        get :magiq
        put :update_comparison
      end
    end

    resources :evaluations do
      collection do
        get :rank
        get :smart
        get :pairwise
        get :direct
        get :adjust
        put :update_rank
        put :update_smart
        put :update_pairwise
        put :update_direct
        put :update_evaluation
      end
    end

    member do
      get :smart_compare
      get :pairwise_compare
      get :magiq_compare
      put :update_smart
      put :update_pairwise
      put :update_magiq
      get :new_sub
      post :create_sub
    end

    resources :ratings do
      collection do
        get :aggregate_detail
        get :aggregate_summary
      end
    end
    
    resources :results do
      collection do
        get :sensitivity_chart
        get :rank
        get :flow_diagram
        get :sankey
        get :benefit_cost
      end
    end

    resources :comments, only: [:edit, :create, :update, :destroy]
  end

  resources :products do
    resources :product_watch_lists, only: [:create, :destroy]
    collection do
      get   :featured
      get   :top
    end
    post :like
    post :unlike
    post :watch
    post :unwatch
    get  :info_panel
  end

  resources :categories

  resources :notifications, only: [:show] do
    member do
      post :dismiss
    end
  end

  resources :organizations do
    member do
      get    :members, to: :new_members
      post   :members, to: :add_members
      match 'members/:member_id', to: :remove_members, via: :delete, as: 'remove_member'
    end
  end
  
  match 'articles/:article_id/rate', to: 'ratings#evaluate', as: 'article_rate'
  match 'articles/:article_id/results', to: 'results#results', as: 'article_results'
  match 'articles/:article_id/sensitivity_analysis', to: 'results#sensitivity_analysis', as: 'article_sensitivity_analysis'
  match 'articles/:article_id/sensitivity_chart', to: 'results#sensitivity_analysis', as: 'article_sensitivity_chart'
  match 'articles/:article_id/flow_diagram', to: 'results#flow_diagram', as: 'article_flow_diagram'
  match 'articles/:article_id/sankey', to: 'results#sankey', as: 'article_sankey'
  match 'articles/:article_id/benefit_cost', to: 'results#benefit_cost', as: 'article_benefit_cost'
  match 'articles/:article_id/incomplete', to: 'results#incomplete', as: 'article_incomplete'

  match '/alternatives/:alternative_id/comments', to: 'comments#create', as: 'alternative_comments', via: :post
  match '/alternatives/:alternative_id/comments/new', to: 'comments#new', as: 'new_alternative_comment', via: :get
  match '/alternatives/:alternative_id/comments/:id', to: 'comments#update', as: 'alternative_comment', via: :put
  match '/alternatives/:alternative_id/comments/:id/edit', to: 'comments#edit', as: 'edit_alternative_comment', via: :get
  match '/alternatives/:alternative_id/comments/:id', to: 'comments#destroy', as: 'alternative_comment', via: :destroy
  match '/alternatives/:alternative_id/comments/:id/reply', to: 'comments#reply', as: 'reply_alternative_comment', via: :post
  match '/articles/:article_id/comments/:id/reply', to: 'comments#reply', as: 'reply_article_comment', via: :post
  match '/criteria/:criterion_id/comments/:id/reply', to: 'comments#reply', as: 'reply_criterion_comment', via: :post
  match '/articles/:article_id/comments/:id/new_reply', to: 'comments#new_reply', as: 'new_reply_article_comment', via: :get
  match '/alternatives/:alternative_id/comments/:id/new_reply', to: 'comments#new_reply', as: 'new_reply_alternative_comment', via: :get
  match '/criteria/:criterion_id/comments/:id/new_reply', to: 'comments#new_reply', as: 'new_reply_criterion_comment', via: :get

  match 'articles/:article_id/common_properties/:property', to: 'articles#common_properties', as: 'article_common_properties'
  match 'articles/:article_id/update_common_properties/:property', to: 'articles#update_common_properties', via: :post, as: 'article_update_common_properties'
  match 'articles/:article_id/edit_common_properties', to: 'articles#edit_common_properties', via: :get, as: 'article_edit_common_properties'
  match 'articles/:article_id/common_properties', to: 'articles#save_common_properties', via: :put, as: 'article_save_common_properties'

  match 'articles/:article_id/alternatives/:id/add_property_row', to: 'alternatives#add_property_row', as: 'add_property_row'

  match 'featured_articles', to: 'articles#featured'
  match 'top_articles', to: 'articles#top'
  match 'new_and_updated', to: 'articles#new_and_updated'
  match 'my_articles', to: 'articles#my_articles'
  match 'participating', to: 'articles#participating'
  match 'watch_list', to: 'articles#watch_list'

  match 'current_user', to: 'users#current'

  match 'plans', to: 'home#plans'
  
  scope '/manage', :as => 'manage' do
    resources :featured_articles
    resources :featured_products
    resources :categories
    controller 'admin/manage' do
      match 'users' => :users
      match 'user/:user_id' => :user, as: 'user', via: :get
      match 'user/:user_id' => :update_user_account, as: 'user', via: :post
      match 'setting' => :settings
    end
  end

  scope '/api', as: 'api' do
    match 'articles/:article_id/rate', to: 'api/ratings#evaluate', as: 'article_rate'
    match 'articles/:article_id/results', to: 'api/results#results', as: 'article_results'
    match 'articles/:article_id/sensitivity_analysis', to: 'api/results#sensitivity_analysis', as: 'article_sensitivity_analysis'
    match 'articles/:article_id/sensitivity_chart', to: 'api/results#sensitivity_analysis', as: 'article_sensitivity_chart'
    match 'articles/:article_id/flow_diagram', to: 'api/results#flow_diagram', as: 'article_flow_diagram'
    match 'articles/:article_id/sankey', to: 'api/results#sankey', as: 'article_sankey'
    match 'articles/:article_id/benefit_cost', to: 'api/results#benefit_cost', as: 'article_benefit_cost'
    match 'articles/:article_id/incomplete', to: 'api/results#incomplete', as: 'article_incomplete'
  end

  match 'public_errors', to: 'public_errors#routing'
  match '*a', :to => 'public_errors#routing'
  

end

app/controllers/articles_controller.rb
# Copyright (c) 2012 Medhi Widjaja

require 'will_paginate/array'

class ArticlesController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :new_and_updated, :featured, :show]
  before_filter :article_menu
  before_filter :disable_right_frame!, only: [:show, :create, :new, :edit, :edit_common_properties]
  before_filter :disable_left_frame!, except: [:show, :create, :new, :edit, :edit_common_properties] 

  # GET /articles
  # GET /articles.json
  # def index
  #   @articles = Article.public.asc(:_id).paginate(page: params[:page])
    
  #   respond_to do |format|
  #     format.html # index.html.erb
  #     format.json { render json: @articles }
  #   end
  # end

  # TODO: filter only id, title, description, user (as necessary)
  def index
    terms = params[:q]
    unless terms.blank?
      @articles = Article.search page: params[:page] do
        query { string terms }
        filter :terms, :visibility => ['public']
      end
      @terms = terms
      respond_to do |format|
        format.html # search.html.erb
        format.json do
          json_array = @articles.collect do |n|
            n.as_json.merge Hash["img" => n.load.pic_snippet]  
            # we have to load the item from the database, because @articles returned by Tire
            # doesn't contain 'real' articles
          end
          if params[:callback]
            render json: json_array, callback: params[:callback]
          else
            render json: json_array
          end
        end
      end
    end
    @terms = terms
  end

  def new_and_updated
    @new_and_updated =  Article.public.new_and_updated(30).paginate(page: params[:page])
    json_array = @new_and_updated.collect do |n|
      n.as_json.merge Hash["img" => n.pic_snippet]
    end

    respond_to do |format|
      format.html # new_and_updated.html.slim
      format.json do 
        if params[:callback]
          render json: json_array, callback: params[:callback]
        else
          render json: json_array
        end
      end
    end
  end    

  def featured
    @featured = FeaturedArticle.current.desc(:expire_date).paginate(page: params[:page])
    respond_to do |format|
      format.html 
      format.json { render json: @featured }
    end
  end

  def top
    # TODO: sort and filter by some criteria
    @articles = Article.public.paginate(page: params[:page])
    respond_to do |format|
      format.html 
      format.json { render json: @featured }
    end
  end


  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.without(:aggregate).find(params[:id])
    authorize! :read, @article
    @participations = @article.participations.all
    @article_id = @article.id
    @alternatives = @article.alternatives
    @comments = @article.root_comments.desc(:created_at)
    @commentable = @article
    if user_signed_in?
      @comment = @article.comments.new user:current_user
    end
    respond_to do |format|
      format.html # show.html.erb
      # format.json { render json: @article }
      format.json { render json: {id:@article.slug, title: @article.title, description:@article.description, author:@article.user.id} }
    end
  end

  # GET /articles/new
  # GET /articles/new.js
  def new
    @article = current_user.articles.build
    # Set default visibility: 'public' for Free account, and 'private' for others
    @article.visibility = current_user.account == 'free' ? 'public' : 'private'
    authorize! :create, @article
    @user = @article.user
    @categories = Category.all
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
    authorize! :update, @article
    @article_id = @article.id.to_s
    @common_property = @article.common_properties
    # @participants = @article.participations.collect { |p| p.user }
    @participations = @article.participations.all
    @categories = Category.all
    # session[:article_id] = @article.id
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.build(params[:article])
    authorize! :create, @article
    @user = @article.user
    @categories = Category.all
    respond_to do |format|
      if @article.save
        format.html { redirect_to article_path(@article.slug), notice: 'Article was successfully created.' }
        format.js { redirect_to article_path(@article.slug), notice: 'Article was successfully created.' }
        # format.json { render json: @article, status: :created, location: @article }
        format.json do
          if params[:callback]
            render json: @article, status: :created, location: @article, callback: params[:callback]
          else
            render json: @article, status: :created, location: @article
          end
        end
      else
        format.html { render action: "new" }
        format.js { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])
    authorize! :update, @article
    @categories = Category.all
    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    authorize! :destroy, @article
    @article.destroy

    respond_to do |format|
      format.html { redirect_to my_articles_path }
      format.json { head :no_content }
    end
  end

  def my_articles
    @user = current_user
    authorize! :read, @user
    @articles = @user.articles.desc(:updated_at).paginate(page: params[:page])
    #TODO: Optimize! cache list in an array stored in User class
    # using @user.articles.desc(:updated_at).map {|a| {label:a.title, id:a.to_param}}
    # update every time Article is saved (after_save :update_list)
  end

  def participating
    @user = current_user
    authorize! :read, @user
    respond_to do |format|
      format.html do # participating.html.slim
        @articles = Participation.where(user:@user).all_active.desc(:updated_at)
                      .collect{ |p| p.article unless p.article.nil? || p.article.user == @user }
                      .compact.paginate(page: params[:page])
      end
      # format.json do # participating.json.rabl
      #   @articles = Participation.where(user:@user).all_active.desc(:updated_at).limit(20)
      #                 .collect{ |p| p.article unless p.article.nil? || p.article.user == @user }
      #                 .compact
      # end
    end
  end

  def watch_list
    @user = current_user
    authorize! :read, @user
    @articles = @user.watch_list.articles.desc(:updated_at).paginate(page: params[:page])
    respond_to do |format|
      format.html  # watch_list.html.slim
      format.json do
        if params[:callback]
          render json: @articles, callback: params[:callback]
        else
          render json: @articles
        end
      end
    end
  end

  def add_property
    @article = Article.find(params[:article_id])
    authorize! :modify, @article
    @article_id = @article.id.to_s
    @property = params[:property]
    @commit = params[:commit]
    @article.add_common_property(@property) unless @commit == "Cancel" || @property.blank?
    respond_to do |format|
      format.js 
    end
  end

  def common_properties
    @article = Article.find(params[:article_id])
    authorize! :view, @article
    @property = params[:property]
    @alternatives = @article.alternatives.asc(:position)
    @alternatives.asc(:position).each do |alt|
      alt.properties.build(k: @property)
    end
    respond_to do |format|
      format.js
      format.html
    end
  end

  def update_common_properties
    article = Article.find(params[:article_id])
    authorize! :modify, article
    property = params[:property]
    alternatives = article.alternatives
    cost = params[:cost] == "yes"    
    entries = params[:alternatives]

    entries.each do |entry|
      alt_id = entry.first
      value = entry.last  
      p = alternatives.find(alt_id).properties.where(k: property).first
      if p 
        p.set(:v, value)
        p.set(:cost, cost)
      else
        alternatives.find(alt_id).properties.create(k: property, v: value, cost: cost)
      end
    end
    article.model_time_stamp

    flash[:notice] = "Common properties for '#{property}' were successfully saved."
    redirect_to article_alternatives_path(article.id)
  end

  def edit_common_properties
    @article = Article.find(params[:article_id])
    authorize! :modify, @article
    @alternatives = @article.alternatives
    @common_properties = @article.common_properties
  end

  def save_common_properties
    @article = Article.find(params[:article_id])
    authorize! :update, @article

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to article_alternatives_path, notice: 'Common properties were updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit_common_properties" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_alternative
  end

  def update_alternatives_order
    article = Article.find(params[:article_id])
    authorize! :modify, article
    article.attributes = params[:article]
    render nothing: true
  end

  def show_participants
    @article = Article.find(params[:article_id])
    @participants = @article.participations
  end

  def like

app/helpers/articles_helper.rb
# Copyright (c) 2012 Medhi Widjaja

module ArticlesHelper
end

app/views/articles/0_article_info.html.slim
#sidepanel.well.well-sidebar
  .section
    .section-title
      | Article by:
    .user-avatar
      = gravatar_for @article.user
    .article-owner
      = @article.user.name
    hr
  .section
    .section-title
      | Participants ( #{@article.participations.all_active.count} )
    a.resize-button data-toggle="collapse" data-target="#list-of-participants" href="#" 
      i.icon-resize-vertical
    #list-of-participants.collapse.in
      = render partial:'participations/avatars', locals: { participations: @article.participations }
      
      =' link_to "List", article_participations_path(@article.slug), class:"btn btn-mini pjax"
      -if current_user == @article.user
        =' link_to "Invite", invite_article_participations_path(@article.slug), class:"btn btn-primary btn-mini pjax"
      -elsif !@article.participation_by(current_user)
        =' link_to "Request to join", new_request_article_participations_path(@article.slug), class:"btn btn-warning btn-mini pjax"

  .section
    .section-title 
      | Article Stats
    a.resize-button data-toggle="collapse" data-target="#stat-contents" href="#" 
      i.icon-resize-vertical
    #stat-contents.collapse.in
      .article-date 
        = @article.created_at.strftime("Created on %m/%d/%Y")
      .article-date 
        = "Updated #{time_ago_in_words(@article.updated_at)} ago"

      ul.article-stats
        li.article-view 
          i.icon-eye-open
          .stat-label = "Watch" 
          #watch-count.stat-value = @article.watch_count   
          // FIXME
        li.article-appreciation
          i.icon-gift
          .stat-label = "Appreciation" 
          #appreciations-count.stat-value = "000"
        li.article-comments 
          i.icon-comment
          .stat-label = "Comments" 
          #comments-count.stat-value = "000"
  .section
    .section-title Share article
    // FIXME
    = image_tag('facebook_like.png')
    ' &nbsp;
    = image_tag('tweet.png')
    ' &nbsp;
    = image_tag('g_plus.png')
  .section
    .section-title Article tags
    // FIXME
    .tag-group
      span.badge Tag
      span.badge is not
      span.badge done
      ' 
      span.badge yet
      ' 
      span.badge Fix me!
      '  
      span.badge This is a long tag
  .section
    .section-title Article sponsor
    .thumbnail style="background-color: #e8653a"
      div style="height:120px;" 
        br
        p style="color: white; font-family: 'Garamond'; font-size:50px"  
          | Sponsor



      

app/views/articles/0new.html.slim
- provide :title, "New Article"

#content-box
	.widget
		.widget-header
			i.icon-file
			h3 New article
		.well.well-widget-content
			.widget-content-title Create new article
			= form_for @article do |form|
				== render partial: 'form', locals: {f: form}
				#toolbar.button-toolbar
				  = form.submit 'Save', class:'btn btn-primary'
				  = link_to my_articles_path, class:'btn' do
				    i.icon-remove
				    |  Cancel

app/views/articles/_article.html.slim
tr.article
	td.article
		.title
			= link_to article.title.truncate(50), article
			-if can? :edit, article
				span.tool
					a href=edit_article_path(article.slug)
						i.icon-edit
						'  Edit
			.timestamp
				i.icon-time
				=' " #{time_ago_in_words(article.updated_at)} ago"	
		.picture
			- url = pic_snippet(article.description)
			= image_tag url, size:'65x65' unless url.nil?
		.description.formatted-output
			= raw truncate_html(description_snippet(article.description),500)
		.info
			span.author
				i.icon-user
				' &nbsp;Author:
				= link_to article.user.name, user_path(article.user.id)
				' &nbsp;
			span.star
				/ FIXME: This is just a stub.
				i.icon-star
				i.icon-star
				i.icon-star
				i.icon-star-empty
				i.icon-star-empty
			/ .social_networks
			/ 	= image_tag('facebook_like.png')
			/ 	' &nbsp;
			/ 	= image_tag('tweet.png')
			/ 	' &nbsp;
			/ 	= image_tag('g_plus.png')

app/views/articles/add_property.js.erb
<% if @commit=='Add' && @property != "" %>
	$("li.cprop:last-child").after("<li class='cprop'><a href='<%= article_common_properties_path(@article, URI.escape(@property)) %>' class='pjax'> <%= @property%> </a></li>");
<% end %>
$(".new_form").remove();
$("#cp_new").show()

app/views/articles/common_properties.html.slim
- provide :title, "Common Properties"

- unless pjax_request?
	- content_for :javascript do
		= javascript_include_tag "alternative.js"
		= javascript_include_tag "properties.js"
	  
	- content_for :left_frame do
		= render 'alternatives/alternative_sidepanel'
		= render partial: 'articles/common_property_list', locals: { article: @article, id: @article_id }

.widget
	.widget-header
		h3 Input common properties
	.well.well-widget-content
		.widget-content-title Property

		-if can? :modify, @article
			= form_tag action: 'update_common_properties', id: @article.id, class:'common_properties' do

				table.properties.table-striped.table-condensed style="width:60%"
					thead
						tr
							th.align-left Alternative
							th.align-left = @property
					tbody
						-@alternatives.each do |alternative|
							tr
								td
									= alternative.title
								td.number
									= text_field_tag "alternatives[#{alternative.id}]", alternative.properties.where(k: @property).first.nil? ? '' : alternative.properties.where(k: @property).first.v

				label.checkbox
					-property = @alternatives.first.properties.where(k: @property).first
					= check_box_tag 'cost', 'yes', property.nil? ? false : property.cost
					|  Use this property as 
					strong Cost 
					| for Cost-Benefit analysis

				br

				#toolbar.button-toolbar
					= submit_tag 'Save', class:"btn btn-primary"

					= link_to '<i class="icon-remove"></i> Cancel'.html_safe, article_alternatives_path(@article.id), class: "btn"
		-else
				table#properties.table-striped.table-condensed style="width:60%"
					thead
						tr
							th.align-left Alternative
							th.align-left = @property
					tbody
						-@alternatives.each do |alternative|
							tr
								td
									= alternative.title
								td 
									= alternative.properties.where(k: @property).first.nil? ? '' : alternative.properties.where(k: @property).first.v

app/views/articles/edit.html.slim
- provide :title, "Edit Article"
- content_for :left_frame do
 	= render partial: 'articles/article_sidepanel'

#content-box
	.widget
		.widget-header
			i.icon-edit
			h3 Edit Article
		.well.well-widget-content
			.widget-content-title
				| Editing article
			= form_for @article do |form|
				== render partial: 'form', locals: {f: form}

				#toolbar.button-toolbar
				  = form.submit 'Save', class:'btn btn-primary', disable_with: 'Please wait...'
				  = link_to @article, class:'btn' do
				    i.icon-remove
				    |  Cancel

				  -if request[:action] == 'edit'
				    = link_to @article, 
				        method: :delete,
				        class: "btn btn-danger pull-right", 
				        confirm: "  This will delete the article and\nall related criteria and alternatives.\n\nAre you sure?", 
				        title: @article.title do
				      i.icon-trash
				      |  Delete

app/views/articles/index.html.slim
- provide :title, 'Search articles'

.widget
	-unless @terms.blank?
		.widget-header
			i.icon-search
			h3 Searched for: #{@terms}

		.well.well-widget-content

			table.table.table-bordered.articles
				- @articles.each do |article|
					= render partial: 'article', locals: { article: article.load, terms: @terms }

			= page_navigation_links @articles

	-else
		.widget-header
			i.icon-search
			h3 Not found

		.well.well-widget-content
			br
			.hero-unit
				h1 Looks like...
				| we couldn't find the page you requested.
				.error-options
					ul.list
						li
							| Try searching for similar articles, or

						li
							| Browse 
							= link_to 'recent articles', new_and_updated_path 

app/views/articles/like.js.erb
$("#like-count").html("<%= @article.likes %>");
$("#like-btn").attr("disabled", true).html("<i class='icon-thumbs-up'/>  I like");

app/views/articles/new.html.slim
- provide :title, "New Article"

- content_for :left_frame do
	= render "users/profile_sidepanel"

#content-box
	.widget
		.widget-header
			i.icon-file
			h3 New article
		.well.well-widget-content
			.widget-content-title Create new article

			= form_for @article, url: articles_path, method: :post do |form|
				== render partial: 'form', locals: {f: form}
				#toolbar.button-toolbar
					= form.submit 'Save', class:'btn btn-primary'
					= link_to my_articles_path, class:'btn' do
						i.icon-remove
						|  Cancel

app/views/articles/new.js.erb
$("#new-article-modal").html("<%= escape_javascript(render('articles/modal_new')) %>");
$("#new-article-modal").modal({keyboard: true, backdrop: false});
$("#new-article-modal").modal("show");
$('.wysihtml5').each(function(i, elem) {
	$(elem).wysihtml5();
});

app/views/articles/participating.html.slim
- provide :title, "Participating"
#content-box
	.widget
		.widget-header
			i.icon-group
			h3 = "Articles I'm participating in"
		.well.well-widget-content
			- unless @articles.empty?
			  table.table.table-bordered.articles
			    = render @articles
			  = page_navigation_links @articles
			- else 
				div 
					h4 You are not participating in any articles.
					

app/views/articles/show.js.erb
$("#content-box").html("<%= escape_javascript(render(partial:'article_content')) %>")

app/views/articles/show_participants.html.slim
.widget
  .widget-header
    i.icon-file
    h3 Participants
  .well.well-widget-content
    .widget-content-title List of participants
    div style="overflow: auto"
      table.table.table-condensed.table-bordered.table-striped.props-table
        thead
          tr
            th No
            th Avatar
            th Name
            th Status
            th Weight
            - if @article.allow_edit? current_user
              th Action
        tbody
          - i=0
          - @participants.each do |p|
            tr
              td = i+=1
              td 
                = gravatar_for(p.user, size: 20)
              td = p.username
              td = p.status
              td = p.weight
              - if @article.allow_edit? current_user
                td = link_to "Edit", edit_article_participation_path(@article.id, p.id), class: "btn"
    br
    -if @article.allow_edit? current_user
      #toolbar.button-toolbar
        = link_to "Invite new participants", article_invite_path(@article.id), class: "btn"
        '
        = link_to "Assign weights", "#", class: "btn"

javascript:
  $(function() {
    $('.props-table').dataTable( {
        "bPaginate": false,
        "bLengthChange": false,
        "bFilter": false,
        "bSort": true,
        "bInfo": false,
        "bAutoWidth": true
      } );
    $.extend( $.fn.dataTableExt.oStdClasses, {
      "sSortAsc": "header headerSortDown",
      "sSortDesc": "header headerSortUp",
      "sSortable": "header"
      } );
  });
  

app/views/articles/top.html.slim
-provide :title, 'Articles'

/ TODO: top articles filtered and sorted by some criteria (most viewed, most participated, etc.)
.widget
	.widget-header
		i.icon-star-empty
		h3 Top Articles
	.well.well-widget-content.content-with-table

		table.table.table-bordered.articles
		  - @articles.each do |article|
				= render partial: 'article', locals: { article: article }

		= page_navigation_links @articles