config/routes.rb
Wisdm::Application.routes.draw do

  resources :catalogs

  root to: "home#index"

  devise_for :users,
             :controllers  => {
               :registrations => 'my_devise/registrations',
               :sessions      => 'my_devise/sessions',
               :passwords     => 'my_devise/passwords',
               :unlocks       => 'my_devise/unlocks',
               :confirmations => 'my_devise/confirmations'
             }
  
  resources :users do
    collection do
      get :index
    end
    member do
      get :show, :following, :followers, :my_articles, :account
    end
    resources :friend_lists, only: [:create, :destroy]
  end

  resources :articles do

    post :add_property
    post :update_alternatives_order
    get  :show_participants
    post :like
    
    resources :alternatives do
      collection do
        get  :search
        post :search
        post :add
      end
    end

    resources :criteria, only: [:index, :create, :new]

    resources :watch_lists, only: [:create, :destroy]
    resources :participations do
      collection do
        get  :invite
        post :send_invitation
        get  :new_request
        post :send_request
        get  :assign_weights
        post :update_weights
      end
      member do
        post :approve
        post :confirm
      end
    end

    resources :comments, only: [:edit, :create, :update, :destroy]
  end

  resources :criteria do
    get :tree
    post :move
    get :aggregate_detail
    get :aggregate_summary

    resources :comparisons do
      collection do
        post :compare
        get :smart
        get :pairwise
        get :magiq
        put :update_comparison
      end
    end

    resources :evaluations do
      collection do
        get :rank
        get :smart
        get :pairwise
        get :direct
        get :adjust
        put :update_rank
        put :update_smart
        put :update_pairwise
        put :update_direct
        put :update_evaluation
      end
    end

    member do
      get :smart_compare
      get :pairwise_compare
      get :magiq_compare
      put :update_smart
      put :update_pairwise
      put :update_magiq
      get :new_sub
      post :create_sub
    end

    resources :ratings do
      collection do
        get :aggregate_detail
        get :aggregate_summary
      end
    end
    
    resources :results do
      collection do
        get :sensitivity_chart
        get :rank
        get :flow_diagram
        get :sankey
        get :benefit_cost
      end
    end

    resources :comments, only: [:edit, :create, :update, :destroy]
  end

  resources :products do
    resources :product_watch_lists, only: [:create, :destroy]
    collection do
      get   :featured
      get   :top
    end
    post :like
    post :unlike
    post :watch
    post :unwatch
    get  :info_panel
  end

  resources :categories

  resources :notifications, only: [:show] do
    member do
      post :dismiss
    end
  end

  resources :organizations do
    member do
      get    :members, to: :new_members
      post   :members, to: :add_members
      match 'members/:member_id', to: :remove_members, via: :delete, as: 'remove_member'
    end
  end
  
  match 'articles/:article_id/rate', to: 'ratings#evaluate', as: 'article_rate'
  match 'articles/:article_id/results', to: 'results#results', as: 'article_results'
  match 'articles/:article_id/sensitivity_analysis', to: 'results#sensitivity_analysis', as: 'article_sensitivity_analysis'
  match 'articles/:article_id/sensitivity_chart', to: 'results#sensitivity_analysis', as: 'article_sensitivity_chart'
  match 'articles/:article_id/flow_diagram', to: 'results#flow_diagram', as: 'article_flow_diagram'
  match 'articles/:article_id/sankey', to: 'results#sankey', as: 'article_sankey'
  match 'articles/:article_id/benefit_cost', to: 'results#benefit_cost', as: 'article_benefit_cost'
  match 'articles/:article_id/incomplete', to: 'results#incomplete', as: 'article_incomplete'

  match '/alternatives/:alternative_id/comments', to: 'comments#create', as: 'alternative_comments', via: :post
  match '/alternatives/:alternative_id/comments/new', to: 'comments#new', as: 'new_alternative_comment', via: :get
  match '/alternatives/:alternative_id/comments/:id', to: 'comments#update', as: 'alternative_comment', via: :put
  match '/alternatives/:alternative_id/comments/:id/edit', to: 'comments#edit', as: 'edit_alternative_comment', via: :get
  match '/alternatives/:alternative_id/comments/:id', to: 'comments#destroy', as: 'alternative_comment', via: :destroy
  match '/alternatives/:alternative_id/comments/:id/reply', to: 'comments#reply', as: 'reply_alternative_comment', via: :post
  match '/articles/:article_id/comments/:id/reply', to: 'comments#reply', as: 'reply_article_comment', via: :post
  match '/criteria/:criterion_id/comments/:id/reply', to: 'comments#reply', as: 'reply_criterion_comment', via: :post
  match '/articles/:article_id/comments/:id/new_reply', to: 'comments#new_reply', as: 'new_reply_article_comment', via: :get
  match '/alternatives/:alternative_id/comments/:id/new_reply', to: 'comments#new_reply', as: 'new_reply_alternative_comment', via: :get
  match '/criteria/:criterion_id/comments/:id/new_reply', to: 'comments#new_reply', as: 'new_reply_criterion_comment', via: :get

  match 'articles/:article_id/common_properties/:property', to: 'articles#common_properties', as: 'article_common_properties'
  match 'articles/:article_id/update_common_properties/:property', to: 'articles#update_common_properties', via: :post, as: 'article_update_common_properties'
  match 'articles/:article_id/edit_common_properties', to: 'articles#edit_common_properties', via: :get, as: 'article_edit_common_properties'
  match 'articles/:article_id/common_properties', to: 'articles#save_common_properties', via: :put, as: 'article_save_common_properties'

  match 'articles/:article_id/alternatives/:id/add_property_row', to: 'alternatives#add_property_row', as: 'add_property_row'

  match 'featured_articles', to: 'articles#featured'
  match 'top_articles', to: 'articles#top'
  match 'new_and_updated', to: 'articles#new_and_updated'
  match 'my_articles', to: 'articles#my_articles'
  match 'participating', to: 'articles#participating'
  match 'watch_list', to: 'articles#watch_list'

  match 'current_user', to: 'users#current'

  match 'plans', to: 'home#plans'
  
  scope '/manage', :as => 'manage' do
    resources :featured_articles
    resources :featured_products
    resources :categories
    controller 'admin/manage' do
      match 'users' => :users
      match 'user/:user_id' => :user, as: 'user', via: :get
      match 'user/:user_id' => :update_user_account, as: 'user', via: :post
      match 'setting' => :settings
    end
  end

  scope '/api', as: 'api' do
    match 'articles/:article_id/rate', to: 'api/ratings#evaluate', as: 'article_rate'
    match 'articles/:article_id/results', to: 'api/results#results', as: 'article_results'
    match 'articles/:article_id/sensitivity_analysis', to: 'api/results#sensitivity_analysis', as: 'article_sensitivity_analysis'
    match 'articles/:article_id/sensitivity_chart', to: 'api/results#sensitivity_analysis', as: 'article_sensitivity_chart'
    match 'articles/:article_id/flow_diagram', to: 'api/results#flow_diagram', as: 'article_flow_diagram'
    match 'articles/:article_id/sankey', to: 'api/results#sankey', as: 'article_sankey'
    match 'articles/:article_id/benefit_cost', to: 'api/results#benefit_cost', as: 'article_benefit_cost'
    match 'articles/:article_id/incomplete', to: 'api/results#incomplete', as: 'article_incomplete'
  end

  match 'public_errors', to: 'public_errors#routing'
  match '*a', :to => 'public_errors#routing'
  

end

app/models/notification.rb
# Copyright (c) 2012 Medhi Widjaja

class Notification
  include Mongoid::Document
  include Mongoid::Timestamps
  extend ActiveSupport::Concern

  field :email, 		   type: String
  field :accepted, 	   type: Boolean, default: false
  field :state, 		   type: String,  default: "pending"
  field :accepted_by,  type: String
  field :accepted_at,  type: Time
  field :sender_id,    type: String
  field :sender_name,  type: String
  field :article_id,   type: String
  field :article_name, type: String
  field :body, 			   type: String
  field :model,        type: String
  field :model_id,     type: String
  field :type,         type: String

  belongs_to :user

  index({user_id: 1})
  index({email: 1})

  validates_length_of :body, :in => 0..400

  scope :pending, where(state: 'pending')

  # ClassMethods
  def Notification.new_notice(person, model, type, sender, subject, body="")
    if body.empty?
      case type
      when 'invite'
        body = "Your opinions count. You have been invited to participate in the decision."
      when 'approve'
        body = "Your request to join the decision has been approved."
      when 'request'
        body = "#{sender.name} has requested to join in the decision."
      when 'confirm'
        body = "Yes, #{sender.name} has agreed to join in the decision."
      when 'decline'
        body = "Sorry to decline. Thanks for the invitation."
      when 'reject'
        body = "Sorry, your request cannot be approved at this moment."
      end
    end

    Notification.new user_id: person.id, 
                      email: person.email, 
                      model: model.class, 
                      model_id: model.id,  
                      sender_id: sender.id,
                      sender_name: sender.name,
                      article_id: model.article_id,
                      subject: subject,
                      body: body,
                      type: type
  end

  # Instance methods

  def pending?
    state == 'pending'
  end

  def title
    {'invite' => 'Invitation', 
     'approve' => 'Approval', 
     'request' => 'Request',
     'confirm' => 'Confirmation',
     'decline' => 'Declined',
     'reject' => 'Not approved' }[ self.type ]
  end
end

app/controllers/notifications_controller.rb
# Copyright (c) 2012 Medhi Widjaja

class NotificationsController < ApplicationController
  before_filter :disable_right_frame!, :enable_left_frame!

  def show
    @notification = Notification.find(params[:id])
    authorize! :show, @notification
    @article = Article.find(@notification.article_id)
  end

  def dismiss
    @notification = Notification.find(params[:id])
    authorize! :edit, @notification
    previous_page = params[:page]
    @notification.update_attributes state: 'complete', 
                                   accepted_by: current_user.id, 
                                   accepted_at: Time.now.utc
  end
end

app/views/notifications/_menu_list.html.slim
ul.dropdown-menu
	-current_user.notifications.pending.each do |notification|
		li.dropdown id=notification.id
			= link_to notification_path(notification.id), remote: true do
				.notification-subject-menu 
					= notification.title
				.notification-body-menu  
					= truncate(notification.body, length: 30)

app/views/notifications/_modal_form.html.slim
.modal-header
	a.close data-dismiss="modal" ×
	h3 
		i.icon-inbox
		|   Notice: #{@notification.title}
.modal-body.widget style="margin-bottom:0px"
	-unless Participation.where(id:@notification.model_id).exists?
		.alert.alert-error
			span The user associated with this notification seems to have been deleted from the list of participants.
	.section
		.sldef From
		.srdef = @notification.sender_name
	.section
		.section-title Subject
		.notification-subject 
			strong = @notification.subject
		= @notification.created_at			
	.section
		.section-title Message
		.notification-body 		= @notification.body
		br
	.section
		.section-title Links
		.links 
			p = link_to "Article", article_path(@notification.article_id)
			p = link_to "Sender profile", user_path(@notification.sender_id)

.modal-footer
	-if Participation.where(id:@notification.model_id).exists?
		-case @notification.type
		-when 'invite'
			-if @notification.state == 'pending'
				= form_tag confirm_article_participation_path(@notification.article_id, @notification.model_id), { class:'form-inline' } do 
					= hidden_field_tag 'notification', @notification.id
					= submit_tag "Confirm", class: 'btn btn-primary', disable_with: 'Please wait...'
					= submit_tag "Decline", class: 'btn btn-warning', disable_with: 'Please wait...'
					= link_to "Close", "#", class:'btn', "data-dismiss" => 'modal'
			-else
				= link_to '<i class="icon-remove"></i> Cancel'.html_safe, :back, class: 'btn'
		-when 'request'
			-if @notification.state == 'pending'
				= form_tag approve_article_participation_path(@notification.article_id, @notification.model_id), { class:'form-inline' } do 
					= hidden_field_tag 'notification', @notification.id
					= submit_tag "Approve", class: 'btn btn-primary', disable_with: 'Please wait...'
					= submit_tag "Decline", class: 'btn btn-warning', disable_with: 'Please wait...'
					= link_to "Close", "#", class:'btn', "data-dismiss" => 'modal'
			-else
				= link_to '<i class="icon-remove"></i> Cancel'.html_safe, :back, class: 'btn'
		-else
			= form_tag dismiss_notification_path(@notification.id), class:'form-inline', method: :post, remote: true do 
				= hidden_field_tag 'page', url_for(:back)
				= submit_tag "OK", class: 'btn btn-primary', disable_with: 'Please wait...'
				= link_to "Close", "#", class:'btn', "data-dismiss" => 'modal'					
	-else
		= form_tag dismiss_notification_path(@notification.id), { class:'form-inline' } do 
			= hidden_field_tag 'page', url_for(:back)
			= submit_tag "OK", class: 'btn btn-primary', disable_with: 'Please wait...'
			= link_to "Close", "#", class:'btn', "data-dismiss" => 'modal'

app/views/notifications/dismiss.js.erb
$("#inbox-nr").html("<%= current_user.notifications.pending.count %>");
$("li#<%= @notification.id %>").remove();
$("#notification-modal").modal('hide');

app/views/notifications/show.html.slim
- provide :title, 'Notice'
title Notice

-unless Participation.where(id:@notification.model_id).exists?
	.alert.alert-error
		span The user associated with this notification seems to have been deleted from the list of participants.

.widget
	.widget-header
		i.icon-inbox
		h3 = "Notice: #{@notification.title}"
	.well.well-widget-content
		.section
			.sldef From
			.srdef = @notification.sender_name
			.sldef Time
			.srdef = @notification.created_at

		.section
			.section-title Message
			.notification-subject 
				strong = @notification.subject
			.notification-body 		= @notification.body

		.section
			.section-title Links
			.links 
				p = link_to "Article", article_path(@notification.article_id)
				p = link_to "Sender profile", user_path(@notification.sender_id)

		.btn-toolbar.button-toolbar
			-if Participation.where(id:@notification.model_id).exists?
				-case @notification.type
				-when 'invite'
					-if @notification.state == 'pending'
						= form_tag confirm_article_participation_path(@notification.article_id, @notification.model_id), { class:'form-inline' } do 
							= hidden_field_tag 'notification', @notification.id
							= submit_tag "Confirm", class: 'btn btn-primary'
							= submit_tag "Decline", class: 'btn btn-warning'
							= link_to '<i class="icon-remove"></i> Cancel'.html_safe, :back, class: 'btn pull-right'
					-else
						= link_to '<i class="icon-remove"></i> Cancel'.html_safe, :back, class: 'btn'
				-when 'request'
					-if @notification.state == 'pending'
						= form_tag approve_article_participation_path(@notification.article_id, @notification.model_id), { class:'form-inline' } do 
							= hidden_field_tag 'notification', @notification.id
							= submit_tag "Approve", class: 'btn btn-primary'
							= submit_tag "Decline", class: 'btn btn-warning'
							= link_to '<i class="icon-remove"></i> Cancel'.html_safe, :back, class: 'btn pull-right'
					-else
						= link_to '<i class="icon-remove"></i> Cancel'.html_safe, :back, class: 'btn'
				-else
					= form_tag dismiss_notification_path(@notification.id), class:'form-inline', method: :post, remote: true do 
						= hidden_field_tag 'page', url_for(:back)
						= submit_tag "OK", class: 'btn btn-primary'
						= link_to :back, class: 'btn' do
							i.icon-remove
							|  Close					
			-else
				= form_tag dismiss_notification_path(@notification.id), class:'form-inline', method: :post, remote: true do 
					= hidden_field_tag 'page', url_for(:back)
					= submit_tag "OK", class: 'btn btn-primary'
					= link_to :back, class: 'btn' do
						i.icon-remove
						|  Close

app/views/notifications/show.js.erb
$("#notification-modal").html("<%= escape_javascript(render('notifications/modal_form')) %>");
$("#notification-modal").modal({keyboard: true, backdrop: false});
$("#notification-modal").modal("show");