config/routes.rb
Wisdm::Application.routes.draw do

  resources :catalogs

  root to: "home#index"

  devise_for :users,
             :controllers  => {
               :registrations => 'my_devise/registrations',
               :sessions      => 'my_devise/sessions',
               :passwords     => 'my_devise/passwords',
               :unlocks       => 'my_devise/unlocks',
               :confirmations => 'my_devise/confirmations'
             }
  
  resources :users do
    collection do
      get :index
    end
    member do
      get :show, :following, :followers, :my_articles, :account
    end
    resources :friend_lists, only: [:create, :destroy]
  end

  resources :articles do

    post :add_property
    post :update_alternatives_order
    get  :show_participants
    post :like
    
    resources :alternatives do
      collection do
        get  :search
        post :search
        post :add
      end
    end

    resources :criteria, only: [:index, :create, :new]

    resources :watch_lists, only: [:create, :destroy]
    resources :participations do
      collection do
        get  :invite
        post :send_invitation
        get  :new_request
        post :send_request
        get  :assign_weights
        post :update_weights
      end
      member do
        post :approve
        post :confirm
      end
    end

    resources :comments, only: [:edit, :create, :update, :destroy]
  end

  resources :criteria do
    get :tree
    post :move
    get :aggregate_detail
    get :aggregate_summary

    resources :comparisons do
      collection do
        post :compare
        get :smart
        get :pairwise
        get :magiq
        put :update_comparison
      end
    end

    resources :evaluations do
      collection do
        get :rank
        get :smart
        get :pairwise
        get :direct
        get :adjust
        put :update_rank
        put :update_smart
        put :update_pairwise
        put :update_direct
        put :update_evaluation
      end
    end

    member do
      get :smart_compare
      get :pairwise_compare
      get :magiq_compare
      put :update_smart
      put :update_pairwise
      put :update_magiq
      get :new_sub
      post :create_sub
    end

    resources :ratings do
      collection do
        get :aggregate_detail
        get :aggregate_summary
      end
    end
    
    resources :results do
      collection do
        get :sensitivity_chart
        get :rank
        get :flow_diagram
        get :sankey
        get :benefit_cost
      end
    end

    resources :comments, only: [:edit, :create, :update, :destroy]
  end

  resources :products do
    resources :product_watch_lists, only: [:create, :destroy]
    collection do
      get   :featured
      get   :top
    end
    post :like
    post :unlike
    post :watch
    post :unwatch
    get  :info_panel
  end

  resources :categories

  resources :notifications, only: [:show] do
    member do
      post :dismiss
    end
  end

  resources :organizations do
    member do
      get    :members, to: :new_members
      post   :members, to: :add_members
      match 'members/:member_id', to: :remove_members, via: :delete, as: 'remove_member'
    end
  end
  
  match 'articles/:article_id/rate', to: 'ratings#evaluate', as: 'article_rate'
  match 'articles/:article_id/results', to: 'results#results', as: 'article_results'
  match 'articles/:article_id/sensitivity_analysis', to: 'results#sensitivity_analysis', as: 'article_sensitivity_analysis'
  match 'articles/:article_id/sensitivity_chart', to: 'results#sensitivity_analysis', as: 'article_sensitivity_chart'
  match 'articles/:article_id/flow_diagram', to: 'results#flow_diagram', as: 'article_flow_diagram'
  match 'articles/:article_id/sankey', to: 'results#sankey', as: 'article_sankey'
  match 'articles/:article_id/benefit_cost', to: 'results#benefit_cost', as: 'article_benefit_cost'
  match 'articles/:article_id/incomplete', to: 'results#incomplete', as: 'article_incomplete'

  match '/alternatives/:alternative_id/comments', to: 'comments#create', as: 'alternative_comments', via: :post
  match '/alternatives/:alternative_id/comments/new', to: 'comments#new', as: 'new_alternative_comment', via: :get
  match '/alternatives/:alternative_id/comments/:id', to: 'comments#update', as: 'alternative_comment', via: :put
  match '/alternatives/:alternative_id/comments/:id/edit', to: 'comments#edit', as: 'edit_alternative_comment', via: :get
  match '/alternatives/:alternative_id/comments/:id', to: 'comments#destroy', as: 'alternative_comment', via: :destroy
  match '/alternatives/:alternative_id/comments/:id/reply', to: 'comments#reply', as: 'reply_alternative_comment', via: :post
  match '/articles/:article_id/comments/:id/reply', to: 'comments#reply', as: 'reply_article_comment', via: :post
  match '/criteria/:criterion_id/comments/:id/reply', to: 'comments#reply', as: 'reply_criterion_comment', via: :post
  match '/articles/:article_id/comments/:id/new_reply', to: 'comments#new_reply', as: 'new_reply_article_comment', via: :get
  match '/alternatives/:alternative_id/comments/:id/new_reply', to: 'comments#new_reply', as: 'new_reply_alternative_comment', via: :get
  match '/criteria/:criterion_id/comments/:id/new_reply', to: 'comments#new_reply', as: 'new_reply_criterion_comment', via: :get

  match 'articles/:article_id/common_properties/:property', to: 'articles#common_properties', as: 'article_common_properties'
  match 'articles/:article_id/update_common_properties/:property', to: 'articles#update_common_properties', via: :post, as: 'article_update_common_properties'
  match 'articles/:article_id/edit_common_properties', to: 'articles#edit_common_properties', via: :get, as: 'article_edit_common_properties'
  match 'articles/:article_id/common_properties', to: 'articles#save_common_properties', via: :put, as: 'article_save_common_properties'

  match 'articles/:article_id/alternatives/:id/add_property_row', to: 'alternatives#add_property_row', as: 'add_property_row'

  match 'featured_articles', to: 'articles#featured'
  match 'top_articles', to: 'articles#top'
  match 'new_and_updated', to: 'articles#new_and_updated'
  match 'my_articles', to: 'articles#my_articles'
  match 'participating', to: 'articles#participating'
  match 'watch_list', to: 'articles#watch_list'

  match 'current_user', to: 'users#current'

  match 'plans', to: 'home#plans'
  
  scope '/manage', :as => 'manage' do
    resources :featured_articles
    resources :featured_products
    resources :categories
    controller 'admin/manage' do
      match 'users' => :users
      match 'user/:user_id' => :user, as: 'user', via: :get
      match 'user/:user_id' => :update_user_account, as: 'user', via: :post
      match 'setting' => :settings
    end
  end

  scope '/api', as: 'api' do
    match 'articles/:article_id/rate', to: 'api/ratings#evaluate', as: 'article_rate'
    match 'articles/:article_id/results', to: 'api/results#results', as: 'article_results'
    match 'articles/:article_id/sensitivity_analysis', to: 'api/results#sensitivity_analysis', as: 'article_sensitivity_analysis'
    match 'articles/:article_id/sensitivity_chart', to: 'api/results#sensitivity_analysis', as: 'article_sensitivity_chart'
    match 'articles/:article_id/flow_diagram', to: 'api/results#flow_diagram', as: 'article_flow_diagram'
    match 'articles/:article_id/sankey', to: 'api/results#sankey', as: 'article_sankey'
    match 'articles/:article_id/benefit_cost', to: 'api/results#benefit_cost', as: 'article_benefit_cost'
    match 'articles/:article_id/incomplete', to: 'api/results#incomplete', as: 'article_incomplete'
  end

  match 'public_errors', to: 'public_errors#routing'
  match '*a', :to => 'public_errors#routing'
  

end

app/views/shared/layout/0_header.html.slim
-@user = current_user
header
	a.btn.btn-navbar data-toggle="collapse" data-target=".nav-collapse"
		span.icon-bar
		span.icon-bar
		span.icon-bar
	= link_to logo, root_path, class: "brand"
	nav.nav-collapse
		ul.nav.pull-right
			li
				a href=root_path
					i.icon-home
			-if signed_in? and current_user.admin?
				li.divider-vertical
				li.dropdown
					a.dropdown-toggle href="#" data-toggle="dropdown"
						i.icon-cog
						|  Admin 
						b.caret
					ul.dropdown-menu
						li
							a href=manage_featured_articles_path
								i.icon-star-empty
								|  Manage Featured Articles
						li
							a href=users_path
								i.icon-user
								|  Manage users
						li
							a href=categories_path
								i.icon-th-list
								|  Manage categories
			li.divider-vertical
			li.dropdown
				a.dropdown-toggle href="#" data-toggle="dropdown"
					i.icon-file
					|  Articles 
					b.caret
				ul.dropdown-menu
					li
						a href=featured_articles_path
							i.icon-star-empty
							|  Featured
					li
						a href="#" 
							i.icon-star
							|  Top rated
					li
						a href=new_and_updated_path 
							i.icon-asterisk
							|  New and updated
					-if signed_in?
						li.divider
						li 
							a href=my_articles_path
								i.icon-file
								|  My articles
						li
							= link_to new_article_path, remote: true do
								i.icon-edit
								|  Create new article
			- if user_signed_in?
				li.dropdown
					a.dropdown-toggle href="#" data-toggle="dropdown"
						i.icon-inbox
						'  Inbox
						- pending = current_user.pending_notifications?
						- if pending
							span.badge.badge-error = current_user.notifications.pending.count
							b.caret
					-if pending
						= render partial: 'notifications/menu_list'
				li.divider-vertical
				li.dropdown
					a.dropdown-toggle.user-name href="#" data-toggle="dropdown"
						=' gravatar_for current_user, size: 20
						strong
							=' current_user.name
						b.caret
					ul.dropdown-menu
						li = link_to "Profile", current_user
						li = link_to "Account Settings", edit_user_registration_path
						li = link_to "Following (#{@user.following_count})", following_user_path(@user)
						li = link_to "Followers (#{@user.followers_count})", followers_user_path(@user)
						li.divider
						li = link_to "Sign out", destroy_user_session_path, method: :delete
			- else
				li
					= link_to "Sign in", new_user_session_path
				li
					= link_to "Sign up", new_user_registration_path
					

app/views/shared/layout/_admin_navbar.html.slim
.subnavbar
	.subnavbar-inner
		.container
			ul.mainnav
				li.active
					a href="/manage/feature"
						i.icon-star-empty
						span Featured
				li
					a href=users_path
						i.icon-user
						span Users
				li
					a href="#"
						i.icon-th
						span ...
				li
					a href="#"
						i.icon-check
						span ...
				li
					a href="#"
						i.icon-cog
						span Settings

app/views/shared/layout/_footer.html.slim
#footer-spacer
#footer
	.container-fluid.clearfix
		.row-fluid
			.span1
			.span2
				h5 Foreplot
				ul.footer-info
					li About us
					li Blog
			.span2
				h5 Legal
				ul.footer-info
					li Terms
					li Privacy
					li Security
			.span2
				h5 Documentations
				ul.footer-info
					li Foreplot Help
					li Forum
					li 
			.span2
				h5 More
				ul.footer-info
					li = link_to "Pricing", plans_path
					li Academic
					li Advertisers
			.span2
				span.copyright © 2013 Foreplot
				br
				br
				div 45832-19278

app/views/shared/layout/_header.html.slim
-@user = current_user

header
	a.btn.btn-navbar data-toggle="collapse" data-target=".nav-collapse"
		span.icon-bar
		span.icon-bar
		span.icon-bar
	= link_to logo, root_path, class: "brand"

	nav.nav-collapse
		ul.nav.pull-right
			li
				.search-form
					= form_tag articles_path, method: :get, class:"form-horizontal" do |form|
						= text_field_tag :q, "", class:"input-medium span3", placeholder:"Search articles..."

			li.divider-vertical
			li rel="tooltip" data-original-title="Home"
				= link_to :root do
					i.icon-home
			-if signed_in? && (current_user.has_role?(:admin) || current_user.has_role?(:editor))
				/li.divider-vertical
				li.dropdown
					a.dropdown-toggle href="#" data-toggle="dropdown"
						i.icon-cogs
						|  Admin 
						b.caret
					ul.dropdown-menu
						-if can? :manage, FeaturedArticle
							li
								a href=manage_featured_articles_path
									i.icon-star-empty
									|  Manage Featured Articles
						-if can? :manage, FeaturedProduct
							li
								a href=manage_featured_products_path
									i.icon-star
									|  Manage Featured Products
						-if can? :manage, Category
							li
								a href=manage_categories_path
									i.icon-th-list
									|  Manage categories
						-if can? :manage, User
							li
								a href=manage_users_path
									i.icon-user
									|  Manage users
			li.divider-vertical
			li.dropdown rel="tooltip" data-original-title="Articles"
				a.dropdown-toggle href="#" data-toggle="dropdown"
					/i.icon-file
					=  "Articles "
					b.caret
				ul.dropdown-menu
					li
						a href=featured_articles_path
							i.icon-star-empty
							|  Featured
					li
						a href="#{top_articles_path}?fn=views" 
							i.icon-star
							|  Top rated
					li
						a href=new_and_updated_path 
							i.icon-asterisk
							|  New and updated
					-if signed_in?
						li.divider
						li 
							h5 &nbsp;&nbsp; Articles...
						li 
							a href=my_articles_path
								i.icon-file
								|  I created
						li
							a href=participating_path
								i.icon-group
								|  I'm participating in
						li
							a href=watch_list_path
								i.icon-eye-open
								|  I'm watching
						li.divider
						li
							= link_to new_article_path do
								i.icon-plus
								|  Create new article
			li.dropdown rel="tooltip" data-original-title="Products"
				a.dropdown-toggle href="#" data-toggle="dropdown"
					/i.icon-truck
					= "Products "
					b.caret
				ul.dropdown-menu
					li
						a href=featured_products_path
							i.icon-star-empty
							|  Featured
					li
						a href=top_products_path
							i.icon-star
							|  Top rated
					li
						a href="#{top_products_path}?fn=views"
							i.icon-asterisk
							|  Popular
					-if signed_in?
						li.divider
						li &nbsp;&nbsp; Products...
						li 
							a href="#{products_path}?o=wn"
								i.icon-file
								|  I created
						li
							a href="#{products_path}?fn=tracking"
								i.icon-eye-open
								|  I'm tracking
						li.divider
						li
							= link_to new_product_path do
								i.icon-plus
								|  Create new product
			- if user_signed_in?
				li.dropdown rel="tooltip" data-original-title="Inbox"
					a.dropdown-toggle href="#" data-toggle="dropdown"
						i.icon-inbox
						/'  Inbox
						- pending = current_user.pending_notifications?
						- if pending
							span.badge.badge-error#inbox-nr = current_user.notifications.pending.count
							b.caret
					-if pending
						= render partial: 'notifications/menu_list'
				li.divider-vertical
				li.dropdown
					a.dropdown-toggle.user-name.user-avatar href="#" data-toggle="dropdown"
						=' gravatar_for current_user, size: 20
						strong
							=' current_user.name
						b.caret
					ul.dropdown-menu
						li = link_to "User Profile", current_user
						li = link_to "Manage Account", edit_user_path(@user)+"?fn=a1"
						li.divider
						li = link_to "Logout", destroy_user_session_path, method: :delete
			- else
				li
					= link_to "Login", new_user_session_path, 'data-skip' => true
				li
					= link_to "Sign up", new_user_registration_path
					

app/views/shared/layout/_modal_divs.html.slim
#new-article-modal.modal.hide.fade style="display:none; width:614px"
#notification-modal.modal.hide.fade

app/views/shared/layout/_model_edit_navbar.html.slim
.subnav.subnav-fixed
	ul.nav.nav-pills
		li.divider-left
		-if user_signed_in?
			li.dropdown
				a.dropdown-toggle href="#" data-toggle="dropdown" style="padding:10px 2px"
					i.icon-file
					b.caret
				ul.dropdown-menu.my-articles
					li
						= link_to new_article_path, remote: true do
							i.icon-edit
							|  Create new article
					li.divider
					li 
						a href=my_articles_path
							strong My articles:
					li 
						#my-articles-list-menu

		li class=link_status('articles')
			a href=article_path(@article)
				i.icon-file
				span  Article
		/ For YC Demo
		/ li class=link_status('alternatives', disabled:(signed_in? ? false : true))
		/ 	a href=article_alternatives_path(@article)
		/ 		i.icon-list-ul
		/ 		span  Alternatives
		/ li class=link_status('criteria', disabled:(signed_in? ? false : true))
		/ 	a href=article_criteria_path(@article)
		/ 		i.icon-sitemap
		/ 		span  Criteria
		/ li class=link_status('rate', disabled:(signed_in? ? false : true))
		/ 	a href=article_rate_path(@article)
		/ 		i.icon-tasks
		/ 		span  Rate

		li class=link_status('alternatives', disabled:false)
			a href=article_alternatives_path(@article)
				i.icon-list-ul
				span  Alternatives
		li class=link_status('criteria', disabled:false)
			a href=article_criteria_path(@article)
				i.icon-sitemap
				span  Criteria
		li class=link_status('rate', disabled:false)
			a href=article_rate_path(@article)
				i.icon-tasks
				span  Rate

		li class=link_status('results')
			a href=article_results_path(@article)
				i.icon-bar-chart
				span  Results
		li.divider-right
		li.article-box
			span.article-label Article:
			span.title = link_to article_title, @article

app/views/shared/layout/_navigation.html.erb
<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>        
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>
<% if user_signed_in? %>
  <li>
  <%= link_to('Edit account', edit_user_registration_path) %>
  </li>
<% else %>
  <li>
  <%= link_to('Sign up', new_user_registration_path)  %>
  </li>
<% end %>