config/routes.rb
Wisdm::Application.routes.draw do

  resources :catalogs

  root to: "home#index"

  devise_for :users,
             :controllers  => {
               :registrations => 'my_devise/registrations',
               :sessions      => 'my_devise/sessions',
               :passwords     => 'my_devise/passwords',
               :unlocks       => 'my_devise/unlocks',
               :confirmations => 'my_devise/confirmations'
             }
  
  resources :users do
    collection do
      get :index
    end
    member do
      get :show, :following, :followers, :my_articles, :account
    end
    resources :friend_lists, only: [:create, :destroy]
  end

  resources :articles do

    post :add_property
    post :update_alternatives_order
    get  :show_participants
    post :like
    
    resources :alternatives do
      collection do
        get  :search
        post :search
        post :add
      end
    end

    resources :criteria, only: [:index, :create, :new]

    resources :watch_lists, only: [:create, :destroy]
    resources :participations do
      collection do
        get  :invite
        post :send_invitation
        get  :new_request
        post :send_request
        get  :assign_weights
        post :update_weights
      end
      member do
        post :approve
        post :confirm
      end
    end

    resources :comments, only: [:edit, :create, :update, :destroy]
  end

  resources :criteria do
    get :tree
    post :move
    get :aggregate_detail
    get :aggregate_summary

    resources :comparisons do
      collection do
        post :compare
        get :smart
        get :pairwise
        get :magiq
        put :update_comparison
      end
    end

    resources :evaluations do
      collection do
        get :rank
        get :smart
        get :pairwise
        get :direct
        get :adjust
        put :update_rank
        put :update_smart
        put :update_pairwise
        put :update_direct
        put :update_evaluation
      end
    end

    member do
      get :smart_compare
      get :pairwise_compare
      get :magiq_compare
      put :update_smart
      put :update_pairwise
      put :update_magiq
      get :new_sub
      post :create_sub
    end

    resources :ratings do
      collection do
        get :aggregate_detail
        get :aggregate_summary
      end
    end
    
    resources :results do
      collection do
        get :sensitivity_chart
        get :rank
        get :flow_diagram
        get :sankey
        get :benefit_cost
      end
    end

    resources :comments, only: [:edit, :create, :update, :destroy]
  end

  resources :products do
    resources :product_watch_lists, only: [:create, :destroy]
    collection do
      get   :featured
      get   :top
    end
    post :like
    post :unlike
    post :watch
    post :unwatch
    get  :info_panel
  end

  resources :categories

  resources :notifications, only: [:show] do
    member do
      post :dismiss
    end
  end

  resources :organizations do
    member do
      get    :members, to: :new_members
      post   :members, to: :add_members
      match 'members/:member_id', to: :remove_members, via: :delete, as: 'remove_member'
    end
  end
  
  match 'articles/:article_id/rate', to: 'ratings#evaluate', as: 'article_rate'
  match 'articles/:article_id/results', to: 'results#results', as: 'article_results'
  match 'articles/:article_id/sensitivity_analysis', to: 'results#sensitivity_analysis', as: 'article_sensitivity_analysis'
  match 'articles/:article_id/sensitivity_chart', to: 'results#sensitivity_analysis', as: 'article_sensitivity_chart'
  match 'articles/:article_id/flow_diagram', to: 'results#flow_diagram', as: 'article_flow_diagram'
  match 'articles/:article_id/sankey', to: 'results#sankey', as: 'article_sankey'
  match 'articles/:article_id/benefit_cost', to: 'results#benefit_cost', as: 'article_benefit_cost'
  match 'articles/:article_id/incomplete', to: 'results#incomplete', as: 'article_incomplete'

  match '/alternatives/:alternative_id/comments', to: 'comments#create', as: 'alternative_comments', via: :post
  match '/alternatives/:alternative_id/comments/new', to: 'comments#new', as: 'new_alternative_comment', via: :get
  match '/alternatives/:alternative_id/comments/:id', to: 'comments#update', as: 'alternative_comment', via: :put
  match '/alternatives/:alternative_id/comments/:id/edit', to: 'comments#edit', as: 'edit_alternative_comment', via: :get
  match '/alternatives/:alternative_id/comments/:id', to: 'comments#destroy', as: 'alternative_comment', via: :destroy
  match '/alternatives/:alternative_id/comments/:id/reply', to: 'comments#reply', as: 'reply_alternative_comment', via: :post
  match '/articles/:article_id/comments/:id/reply', to: 'comments#reply', as: 'reply_article_comment', via: :post
  match '/criteria/:criterion_id/comments/:id/reply', to: 'comments#reply', as: 'reply_criterion_comment', via: :post
  match '/articles/:article_id/comments/:id/new_reply', to: 'comments#new_reply', as: 'new_reply_article_comment', via: :get
  match '/alternatives/:alternative_id/comments/:id/new_reply', to: 'comments#new_reply', as: 'new_reply_alternative_comment', via: :get
  match '/criteria/:criterion_id/comments/:id/new_reply', to: 'comments#new_reply', as: 'new_reply_criterion_comment', via: :get

  match 'articles/:article_id/common_properties/:property', to: 'articles#common_properties', as: 'article_common_properties'
  match 'articles/:article_id/update_common_properties/:property', to: 'articles#update_common_properties', via: :post, as: 'article_update_common_properties'
  match 'articles/:article_id/edit_common_properties', to: 'articles#edit_common_properties', via: :get, as: 'article_edit_common_properties'
  match 'articles/:article_id/common_properties', to: 'articles#save_common_properties', via: :put, as: 'article_save_common_properties'

  match 'articles/:article_id/alternatives/:id/add_property_row', to: 'alternatives#add_property_row', as: 'add_property_row'

  match 'featured_articles', to: 'articles#featured'
  match 'top_articles', to: 'articles#top'
  match 'new_and_updated', to: 'articles#new_and_updated'
  match 'my_articles', to: 'articles#my_articles'
  match 'participating', to: 'articles#participating'
  match 'watch_list', to: 'articles#watch_list'

  match 'current_user', to: 'users#current'

  match 'plans', to: 'home#plans'
  
  scope '/manage', :as => 'manage' do
    resources :featured_articles
    resources :featured_products
    resources :categories
    controller 'admin/manage' do
      match 'users' => :users
      match 'user/:user_id' => :user, as: 'user', via: :get
      match 'user/:user_id' => :update_user_account, as: 'user', via: :post
      match 'setting' => :settings
    end
  end

  scope '/api', as: 'api' do
    match 'articles/:article_id/rate', to: 'api/ratings#evaluate', as: 'article_rate'
    match 'articles/:article_id/results', to: 'api/results#results', as: 'article_results'
    match 'articles/:article_id/sensitivity_analysis', to: 'api/results#sensitivity_analysis', as: 'article_sensitivity_analysis'
    match 'articles/:article_id/sensitivity_chart', to: 'api/results#sensitivity_analysis', as: 'article_sensitivity_chart'
    match 'articles/:article_id/flow_diagram', to: 'api/results#flow_diagram', as: 'article_flow_diagram'
    match 'articles/:article_id/sankey', to: 'api/results#sankey', as: 'article_sankey'
    match 'articles/:article_id/benefit_cost', to: 'api/results#benefit_cost', as: 'article_benefit_cost'
    match 'articles/:article_id/incomplete', to: 'api/results#incomplete', as: 'article_incomplete'
  end

  match 'public_errors', to: 'public_errors#routing'
  match '*a', :to => 'public_errors#routing'
  

end

app/controllers/api/results_controller.rb
# Copyright (c) 2012 Medhi Widjaja

class Api::ResultsController < ApplicationController

  before_filter :disable_right_frame!, :enable_left_frame!
  # before_filter :authenticate_user!
  # before_filter :results_menu
  before_filter :check_completeness
  before_filter :setup, except: [:rank]

  layout 'embedded'

  def results
    @score_table = @result.score_table
    
    @chart_data  = @result.chart_data
    @stacked_chart_data = @result.detail_chart_data
    @objective_labels = @result.criteria_labels
    @alternative_labels = @result.alternative_labels
    @alternative_names = @result.alternative_names
  end

  def rank
    @criterion = Criterion.find(params[:criterion_id])
    @article = @criterion.article
    authorize! :view, @article
    @article_id = @article.id
    criteria = @article.criteria
    root = criteria.root
    @goal = root
    @participation_id = @participation.id
    @alternatives = @article.alternatives
    @aggregate = true if params[:g]
    @result = Result.new @article, @goal, @participation, @aggregate
    @score_table = @result.score_table @criterion

    @chart_data  = @result.chart_data
    @stacked_chart_data = @result.detail_chart_data
    @objective_labels = @result.criteria_labels
    @alternative_labels = @result.alternative_labels
    @alternative_names = @result.alternative_names
  end

  def benefit_cost
    setup
    unless @alternatives.any? { |alt| alt.properties.where(cost:true).first.nil? }
      # @score_table = @result.score_table
      @chart_data = @result.score_table.map {|a| [[a[:cost], a[:score], a[:abbrev].blank? ? a[:title] : a[:abbrev]]] }
      @cost_benefit_table = @result.benefit_cost_table
      @frontier_line = @result.efficient_frontier_lines(@cost_benefit_table)
      @max = @result.score_table.map{|a| a[:score]}.max
      @max = (((@max+0.05)*2).round(1)/2).round(2)
    else
      @no_cost = true
    end
    if params[:chart]
      render partial: "cost_benefit_chart"
    else
      respond_to do |format|
        format.html
      end
    end
  end

  def sensitivity_analysis
    setup
    @criterion = @article.criteria.root.children.first
    unless @criterion.root?
      @sensitivity_chart_data, @sensitivity_chart_labels = @result.sensitivity_data_for_criterion(@criterion.id)
      @chart_data  = @result.chart_data
      @alternative_labels = @sensitivity_chart_labels
      @weight = @criterion.parent.privileged_evaluation_by(@participation_id).score_for_item(@criterion).weight_n
    end
  end

  def sensitivity_chart
    setup
    @criterion = @article.criteria.find(params[:criterion_id])
    unless @criterion.root?
      @sensitivity_chart_data, @sensitivity_chart_labels = @result.sensitivity_data_for_criterion(params[:criterion_id])
      @chart_data  = @result.chart_data
      @alternative_labels = @sensitivity_chart_labels
      @weight = @criterion.parent.privileged_evaluation_by(@participation_id).score_for_item(@criterion).weight_n
    end
  end

  def flow_diagram
    setup
    if params[:criterion_id]  # url is /criteria/criterion_id/results/sankey.json?p=participation_id
      @root = @article.criteria.find(params[:criterion_id])
    else                       # user is requesting root of hierarchy
      @root = @goal
    end
    @sankey_url = "/criteria/#{@root.id.to_s}/results/sankey.json?p=#{@participation_id}"
    @sankey_url += "&g=a" if @aggregate
  end

  def sankey
    setup
    if params[:criterion_id]  # url is /criteria/criterion_id/results/sankey.json?p=participation_id
      @root = @article.criteria.find(params[:criterion_id])
    else                      # user is requesting root of hierarchy
      @root = @goal
    end
    render json: @result.sankey_table(@root)
  end

private

  def check_completeness
    if params[:article_id]
      @article = Article.find(params[:article_id])
    elsif params[:criterion_id]
      criterion = Criterion.find params[:criterion_id]
      criterion.reload if criterion.article.nil?      # Why????
      @article = criterion.article
      # debugger
    end
    if params[:p]
      user = Participation.find(params[:p]).user
    end
    unless user
      if @article.participation_by current_user
        user = current_user
      else
        user = @article.user
      end
    end
    @participation = @article.participations.where(user_id:user.id).first
    if @participation.nil?
      flash[:error] = "No results found for this user"
      redirect_to :back
    else
      unless @participation.evaluation_complete?
        render template: 'results/incomplete'
      end
    end
  end

  def check_group_completeness
  end

  def setup
    authorize! :view, @article
    # @article and @participation defined in check_completeness
    @article_id = @article.id.to_s
    @participation_id = @participation.id
    @criteria = @article.criteria
    @goal = @criteria.root
    @alternatives = @article.alternatives
    @aggregate = true if params[:g]
    @result = Result.new @article, @goal, @participation, @aggregate
    if @result.nil?
      render template: 'results/incomplete'
    end
  end
  
  private
    def results_menu
      session[:link] = 'results'
    end

end

app/views/results/_chart.html.slim
-unless @chart_data.nil?
    #chart.span6 style="height: 300px; margin-left: 50px"
    
    #point-info

    style .jqplot-point-label { font-size: 12px; }
    javascript:
        $(document).ready(function(){
            $.jqplot.config.enablePlugins = true;
            var data = #{ @chart_data };
            var chartLabels = #{{ @alternative_labels }};
            var names = #{{ @alternative_names }};
            plot1 = $.jqplot('chart', [data], {
                // Only animate if we're not using excanvas (not in IE 7 or IE 8)..
                // animate: !$.jqplot.use_excanvas,
                seriesDefaults:{
                    renderer:$.jqplot.BarRenderer,
                    rendererOptions: {
                        varyBarColor: false
                    },
                    pointLabels: {show: true}
                },
                series:[{ pointLabels:{ 
                    show: true, 
                    labels: chartLabels, 
                    edgeTolerance:-25, 
                    escapeHTML: false
                }}],
                axes: {
                    xaxis: {
                        renderer: $.jqplot.CategoryAxisRenderer,
                        show: false,
                        showGridline: false, edgeTolerance:-25, escapeHTML: false,
                        tickOptions: { showGridline: false }
                    },
                    yaxis: {
                        padMax: 1.2
                    }
                },
                grid: {
                    drawBorder: false,
                    shadow: false
                },
                highlighter: {
                    show: true,
                    sizeAdjust: 7.5,
                    tooltipLocation: 'ne',
                    tooltipContentEditor: function(str, seriesIndex, pointIndex) {
                        var objLabel = names[pointIndex];
                        var val = data[pointIndex];
                        return "<span style='font-weight:bold; font-size:12pt; color:#333'>"+val.toPrecision(2)+"</span>";
                    }
                },
                cursor: {
                    show: false
                }
            });
         
            $('#chart').bind('jqplotDataClick', 
                function (ev, seriesIndex, pointIndex, data) {
                    $('#point-info').html('series: '+ names[pointIndex]+', value: '+data[1].toPrecision(3));
                }
            );
        });

app/views/results/_cost_benefit_chart.html.slim
-unless @chart_data.nil?
    #chart style="height: 300px; width: 80%"
    br
    #info1.cb-chart-info

    javascript:
        $(document).ready(function(){
            $.jqplot.config.enablePlugins = true;
            var s1 = #{{ @chart_data }};
            var frontier_line = #{{ @frontier_line }};
            plot1 = $.jqplot('chart', [frontier_line].concat(s1), {
                seriesDefaults: {
                    showline: false,
                    showMarker:true, 
                    pointLabels:{ 
                        show:true, 
                        location:'s', 
                        ypadding:3,
                        edgeTolerance: -25
                    }
                },
                series: [
                    {
                        showline: true,
                        showMarker:false,
                        pointLabels:{ show:false }
                    }
                ],
                axes: {
                    xaxis: {
                        label: 'Cost',
                        labelRenderer: $.jqplot.CanvasAxisLabelRenderer
                    },
                    yaxis: {
                        min: 0.0,
                        max: #{{ @max }},
                        label: 'Benefit',
                        labelRenderer: $.jqplot.CanvasAxisLabelRenderer
                    }
                }
            });
         
            $('#chart').bind('jqplotDataClick', 
                function (ev, seriesIndex, pointIndex, data) {
                    $('#info1').html('<strong>'+data[2]+'</strong><br>Cost: '+ data[0] + '<br>Score: '+data[1].toFixed(3));
                }
            );
        });

app/views/results/_incomplete_evaluation_messages.html.slim
.section style="margin-top: 0px"
	.alert.alert-error
		a.close data-dismiss="alert" ×
		' This user has not completed the criteria or alternative evaluations.

app/views/results/_node_flow_diagram.html.slim
= render partial: 'results_nav_menu'

.widget
	.widget-header.ellipsis
		i.icon-bar-chart
		h3 Flow Diagram
	.well.well-widget-content
		p id="chart"

javascript:
	$(function() {
		var margin = {top: 10, right: 1, bottom: 6, left: 1},
			width = $("#chart").width() - margin.left - margin.right,
			height = 500 - margin.top - margin.bottom;

		var formatNumber = d3.format(",.3f"),
			format = function(d) { return "Weight:" + formatNumber(d); },
			color = d3.scale.category20();

		var svg = d3.select("#chart").append("svg")
			.attr("width", width + margin.left + margin.right)
			.attr("height", height + margin.top + margin.bottom)
			.append("g")
			.attr("transform", "translate(" + margin.left + "," + margin.top + ")");

		var sankey = d3.sankey()
			.nodeWidth(15)
			.nodePadding(10)
			.size([width, height]);

		var path = sankey.link();

		d3.json("#{{@sankey_url}}", function(score) {

		sankey
				.nodes(score.nodes)
				.links(score.links)
				.layout(32);

		var node = svg.append("g")
				.attr("class", "container")
				.selectAll(".node")
				.data(score.nodes)
			.enter().append("g")
				.attr("class", "node")
				.attr("transform", function(d) { return "translate(" + d.x + "," + d.y + ")"; })
				.call(d3.behavior.drag()
				.origin(function(d) { return d; })
				.on("dragstart", function() { this.parentNode.appendChild(this); })
				.on("drag", dragmove));

		node.append("rect")
				.attr("height", function(d) { return d.dy; })
				.attr("width", sankey.nodeWidth())
				.style("fill", function(d) { return d.color = color(d.name.replace(/ .*/, "")); })
				.style("stroke", function(d) { return d3.rgb(d.color).darker(2); })
				.append("title")
				.text(function(d) { return d.name + "\n" + format(d.value); });

		node.append("text")
				.attr("x", -6)
				.attr("y", function(d) { return d.dy / 2; })
				.attr("dy", ".35em")
				.attr("text-anchor", "end")
				.attr("transform", null)
				.text(function(d) { return d.name; })
				.filter(function(d) { return d.x < width / 2; })
				.attr("x", 6 + sankey.nodeWidth())
				.attr("text-anchor", "start");

		var link = svg.append("g")
				.attr("class", "container")
				.selectAll(".link")
				.data(score.links)
			.enter().append("path")
				.attr("class", "link")
				.attr("d", path)
				.style("stroke-width", function(d) { return Math.max(1, d.dy); })
				.style("stroke", function(d) { return d3.rgb(d.source.color).darker(2); } )
				.sort(function(a, b) { return b.dy - a.dy; });

		link.append("title")
				.text(function(d) { return d.source.name + " → " + d.target.name + "\n" + format(d.value); });

		d3.select("#chart svg g")
				.selectAll(".container")
				.sort(function(a, b) { return -1 })			// I know this is cheating.

		function dragmove(d) {
			d3.select(this).attr("transform", "translate(" + d.x + "," + (d.y = Math.max(0, Math.min(height - d.dy, d3.event.y))) + ")");
			sankey.relayout();
			link.attr("d", path);
			}
		});
	});

app/views/results/_rank.html.slim
= render partial: 'results_nav_menu'

.widget
	.widget-header.ellipsis
		i.icon-bar-chart
		h3 Rank and Score
	.well.well-widget-content
		.section
			.widget-content-title With respect to
			h3 
				span.criterion-label
					= @criterion.root? ? "Goal: " : "Criterion: "
				= @criterion.title unless @criterion.nil?
		-unless @participation.evaluation_complete?
			= render 'incomplete_evaluation_messages'
		-else
			.section style="padding-top: 0px"
				.widget-content-title Chart
				#chart-box style="height: 300px; margin-bottom: 10px"
					= render partial: 'chart'
			.section style="padding-top: 0px"
				.widget-content-title Table
				#table-box style="margin-top: 10px; padding:10px 0; position: relative"
					= render partial: 'score_table'

app/views/results/_results_nav_menu.html.slim
- action = params[:action]
- group_tag = @aggregate ? '&g=a' : ''
ul.nav.nav-pills.results
	-if action=='results' or action=='rank'
		li.active
			a Ranking
		li
			a href=article_benefit_cost_path(@article)+"?p=#{@participation.id}"+group_tag Benefit-Cost Analysis
		li
			a href=article_flow_diagram_path(@article)+"?p=#{@participation.id}"+group_tag Flow Diagram
		li
			a href=article_sensitivity_analysis_path(@article)+"?p=#{@participation.id}"+group_tag Sensitivity Analysis
	-elsif action=='benefit_cost'
		li
			a href=article_results_path(@article)+"?p=#{@participation.id}"+group_tag Ranking
		li.active
			a Benefit-Cost Analysis
		li
			a href=article_flow_diagram_path(@article)+"?p=#{@participation.id}"+group_tag Flow Diagram
		li
			a href=article_sensitivity_analysis_path(@article)+"?p=#{@participation.id}"+group_tag Sensitivity Analysis
	-elsif action=='flow_diagram'
		li
			a href=article_results_path(@article)+"?p=#{@participation.id}"+group_tag Ranking
		li
			a href=article_benefit_cost_path(@article)+"?p=#{@participation.id}"+group_tag Benefit-Cost Analysis
		li.active
			a Flow Diagram
		li
			a href=article_sensitivity_analysis_path(@article)+"?p=#{@participation.id}"+group_tag Sensitivity Analysis
	-elsif action=='sensitivity_analysis' or action=='sensitivity_chart'
		li
			a href=article_results_path(@article)+"?p=#{@participation.id}"+group_tag Ranking
		li
			a href=article_benefit_cost_path(@article)+"?p=#{@participation.id}"+group_tag Benefit-Cost Analysis
		li
			a href=article_flow_diagram_path(@article)+"?p=#{@participation.id}"+group_tag Flow Diagram
		li.active
			a Sensitivity Analysis

	

app/views/results/_side_panel.html.slim
.well.side-widget
	.side-widget-header
		a.resize-button data-toggle="collapse" data-target="#widget1" href="#" 
			i.icon-minus.icon-white
	.side-widget-title Results for
	#widget1.collapse.in
		= render partial: 'participants'

.well.side-widget
	.side-widget-header
		a.resize-button data-toggle="collapse" data-target="#widget2" href="#" 
			i.icon-minus.icon-white
	.side-widget-title Criteria Tree
	.side-widget-content
		#widget2.collapse.in
			= content_tag "div", id: "analyses-tree", data: {node: @goal.id.to_s} do
				= image_tag "ajax-loader.gif"

 

app/views/results/_sidepanel.html.slim
.well.side-widget
	.side-widget-header
		a.resize-button data-toggle="collapse" data-target="#widget2" href="#" 
			i.icon-minus
	.side-widget-title Criteria Tree
	.side-widget-content
		-unless @goal.nil?
			#widget2.collapse.in
				= content_tag "div", id: "analyses-tree", data: { article: @article.slug, pid: @participation_id.to_s, node: @goal.id.to_s, group: @aggregate } do
					= image_tag "ajax-loader.gif"

== render partial: 'results/participants'
 

app/views/results/_stacked_chart.html.slim
-unless @stacked_chart_data.nil?
    #stacked-chart.span6 style="height: 300px; margin-left:50px"
    br
    #info2

    javascript:
        $(document).ready(function(){
            $.jqplot.config.enablePlugins = true;
            var s = #{ @stacked_chart_data };
            var ticks = #{{ @alternative_labels }};
            var series = #{{ @objective_labels }};
            var labels = new Array();
            for(var i = 0; i < series.length; i++) { 
                labels = labels.concat( {label: series[i]} )
            };
            plot2 = $.jqplot('stacked-chart', s, {
                // Only animate if we're not using excanvas (not in IE 7 or IE 8)..
                stackSeries: true,
                seriesDefaults:{
                    renderer:$.jqplot.BarRenderer,
                    rendererOptions: {
                        //varyBarColor: true,
                        barMargin: 25
                    },
                    pointLabels: { show: false }
                },
                axes: {
                    xaxis: {
                        renderer: $.jqplot.CategoryAxisRenderer,
                        ticks: ticks,
                        tickOptions: { showGridline: false }
                    }
                },
                highlighter: {
                    show: true,
                    sizeAdjust: 15,
                    tooltipLocation: 'n',
                    tooltipContentEditor: function(str, seriesIndex, pointIndex) {
                        var objLabel = series[seriesIndex];
                        var val = s[seriesIndex][pointIndex];
                        return "<span style='font-weight:bold; font-size:12pt; color:#333'><em>"+objLabel+"</em>: <strong>"+val.toPrecision(2)+"</strong></span>";
                    }
                },
                cursor: {
                    show: false
                },
                grid: {
                    drawBorder: false,
                    shadow: false
                },
                series: labels,
                legend: {
                  show: true,
                  location: 'e',
                  placement: 'outside'
                } 
            });
         
            $('#stacked-chart').bind('jqplotDataClick', 
                function (ev, seriesIndex, pointIndex, data) {
                    $('#info2').tooltip({title:seriesIndex+' point: '+pointIndex+', data: '+data});
                }
            );
        });

app/views/results/benefit_cost.html.slim
- provide :title, 'Benefit / Cost Analysis'

- content_for :left_frame do
	= render partial: 'results/participants'

- content_for :javascript do
	= javascript_include_tag "results.js"

title Benefit/Cost Analysis

#content-box
	= render partial: 'results_nav_menu'

	.widget
		.widget-header.ellipsis
			i.icon-bar-chart
			h3 = "Cost-Benefit Analysis"
		.well.well-widget-content
			-if !@participation.evaluation_complete?
				= render 'incomplete_evaluation_messages'
			-elsif @no_cost
				br
				.alert.alert-error
				  | No cost is setup for this model. Assign one of the alternatives' common properties as cost. (Alternatives / Common Properties / Use this property as Cost for Cost-Benefit analysis)
			-else                     
				.section
					.widget-content-title Rank by Benefit/Cost Ratio
					-unless @cost_benefit_table.nil?
						table.rank-table.table.table-condensed.table-bordered.table-striped
							thead
								tr
									th Rank
									th Alternative
									th.number Score
									th.number Cost
									th.number Normalized Cost
									th.number Benefit/Cost Ratio
							tbody
								- i = 0
								-for alt in @cost_benefit_table
									-unless alt.nil?
										-i+=1
										tr
											td.narrow = i
											td = alt[:title]
											td.number = "#{number_with_precision(alt[:score], precision: 3 )}"
											td.number = alt[:cost]
											td.number = "#{number_with_precision(alt[:cost_n], precision: 3 )}"
											td.number = "#{number_with_precision(alt[:ratio], precision: 3 )}"
				.section style="padding-top: 0px"
					.widget-content-title Chart
					#chart-box
						.alert.alert-info
							a.close data-dismiss="alert" ×
							= "The blue line in the chart represent the <em>efficient frontier,</em> which connects the alternatives worth considering. Any alternative below the efficient frotier line are dominated by those that lie on the line.".html_safe
						= render partial: 'cost_benefit_chart'

						

app/views/results/rank.html.slim
- provide :title, "Rank with respect to #{@criterion.title}"

- content_for :javascript do
	= javascript_include_tag "results.js"

- content_for :left_frame do
	= render 'sidepanel'

= render partial: 'results_nav_menu'

title Rank with respect to #{@criterion.title}

.widget
	.widget-header.ellipsis
		i.icon-bar-chart
		h3 Rank and Score
	.well.well-widget-content
		.section
			.widget-content-title With respect to
			h3 
				span.criterion-label
					= @criterion.root? ? "Goal: " : "Criterion: "
				= @criterion.title unless @criterion.nil?
		-unless @participation.evaluation_complete?
			= render 'incomplete_evaluation_messages'
		-else
			.section style="padding-top: 0px"
				.widget-content-title Chart
				#chart-box style="height: 300px; margin-bottom: 10px"
					= render partial: 'chart'
			.section style="padding-top: 0px"
				.widget-content-title Table
				#table-box style="margin-top: 10px; padding:10px 0; position: relative"
					= render partial: 'score_table'